[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv", "chromium", "chromedriver"]

[phases.install]
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "source .venv/bin/activate && python app.py"